// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/list-applications.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.106.2";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-applications.ts
var list_applications_default = defineTool({
  name: "list_applications",
  title: "List visa applications",
  description: "List visa applications visible to the signed-in user. Clients see their own; staff and admins see all.",
  inputSchema: {
    status: z.enum(["pending", "under_review", "docs_missing", "approved", "rejected"]).optional().describe("Optional status filter."),
    limit: z.number().int().min(1).max(100).optional().describe("Max rows to return (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("visa_applications").select("id, full_name, destination_country, visa_type, status, travel_date, created_at").order("created_at", { ascending: false }).limit(limit ?? 25);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { applications: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-application.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^3.25.76";
var get_application_default = defineTool2({
  name: "get_application",
  title: "Get visa application",
  description: "Fetch the full details of one visa application by its id.",
  inputSchema: { id: z2.string().uuid().describe("Application id (UUID).") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("visa_applications").select("*").eq("id", id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) {
      return { content: [{ type: "text", text: "No application found with that id." }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { application: data }
    };
  }
});

// src/lib/mcp/tools/create-application.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^3.25.76";
var create_application_default = defineTool3({
  name: "create_application",
  title: "Create visa application",
  description: "Submit a new visa application for the signed-in user.",
  inputSchema: {
    full_name: z3.string().trim().min(3).max(100).describe("Applicant full name."),
    passport_number: z3.string().trim().min(6).max(9).regex(/^[A-Za-z0-9]+$/).describe("Passport number, 6-9 alphanumeric characters."),
    destination_country: z3.enum(["Italy", "Portugal", "Greece", "Spain"]).describe("Destination country."),
    visa_type: z3.enum([
      "Study Visa",
      "Work Visa",
      "Family Reunion",
      "Tourist Visa",
      "Business Visa",
      "Residence Visa"
    ]).describe("Visa category."),
    travel_date: z3.string().optional().describe("Intended travel date, YYYY-MM-DD (today or later)."),
    nationality: z3.string().trim().max(60).optional(),
    purpose: z3.string().trim().max(1e3).optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    if (input.travel_date) {
      const d = new Date(input.travel_date);
      const today = new Date((/* @__PURE__ */ new Date()).toDateString());
      if (isNaN(d.getTime()) || d < today || d.getFullYear() > (/* @__PURE__ */ new Date()).getFullYear() + 5) {
        return {
          content: [{ type: "text", text: "travel_date must be today or later, within the next 5 years." }],
          isError: true
        };
      }
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("visa_applications").insert({
      full_name: input.full_name,
      passport_number: input.passport_number.toUpperCase(),
      destination_country: input.destination_country,
      visa_type: input.visa_type,
      travel_date: input.travel_date ?? null,
      nationality: input.nationality ?? null,
      purpose: input.purpose ?? null,
      user_id: ctx.getUserId()
    }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { application: data }
    };
  }
});

// src/lib/mcp/tools/update-application-status.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z4 } from "npm:zod@^3.25.76";
var update_application_status_default = defineTool4({
  name: "update_application_status",
  title: "Update application status",
  description: "Change the status of a visa application. Only staff and admin users are permitted; clients are rejected by access rules.",
  inputSchema: {
    id: z4.string().uuid().describe("Application id (UUID)."),
    status: z4.enum(["pending", "under_review", "docs_missing", "approved", "rejected"]).describe("New status.")
  },
  annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id, status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("visa_applications").update({ status }).eq("id", id).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) {
      return {
        content: [{ type: "text", text: "Update did not apply \u2014 the application was not found or you lack permission." }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { application: data }
    };
  }
});

// src/lib/mcp/tools/list-documents.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z5 } from "npm:zod@^3.25.76";
var list_documents_default = defineTool5({
  name: "list_documents",
  title: "List uploaded documents",
  description: "List document records visible to the signed-in user (metadata only, no file contents). Optionally filter by application.",
  inputSchema: {
    application_id: z5.string().uuid().optional().describe("Only documents linked to this application."),
    limit: z5.number().int().min(1).max(100).optional().describe("Max rows to return (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ application_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("documents").select("id, file_name, status, application_id, created_at").order("created_at", { ascending: false }).limit(limit ?? 25);
    if (application_id) query = query.eq("application_id", application_id);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { documents: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "klhvxeixobvjbmjjevpb";
var mcp_default = defineMcp({
  name: "uzair-visa-consutant",
  title: "Uzair_Visa_Consutant",
  version: "0.1.0",
  instructions: "Tools for Uzair Visa Consultancy. Read and create visa applications, inspect uploaded document records, and (for staff/admin) update application status. All access runs as the signed-in user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_applications_default,
    get_application_default,
    create_application_default,
    update_application_status_default,
    list_documents_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
